// src-vue/App.vue
<script setup lang="ts">
import { ref, onMounted, nextTick } from 'vue'
import { invoke } from '@tauri-apps/api/core'
import { open } from '@tauri-apps/plugin-shell'
import { exit } from '@tauri-apps/plugin-process'
import DancingButton from 'dancing-button'

const index = ref(0)
const tabs = [
  { name: 'Home', key: 'home' },
  { name: 'Option', key: 'opt' },
  { name: 'Shortcut', key: 'shortcut' },
  { name: 'Extension', key: 'ext' },
  { name: 'Custom', key: 'custom' },
  { name: 'Document', key: 'docs' }
]

const loading = ref(false)
const digits = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
const customPaths = ref<string[]>(Array(10).fill(''))

onMounted(async () => {
  await nextTick()
  setTimeout(() => {
    const button = document.querySelector('.liquid-button') as SVGSVGElement
    if (button) {
      new DancingButton(button)
    }
  }, 100)
})

async function make() {
  loading.value = true
  try {
    await invoke('spawn_input')
  } catch (e) {
    console.error(e)
  }
  loading.value = false
}

async function github() {
  await open('https://github.com/seonglae/intuiter')
}

async function exitApp() {
  await exit(0)
}
</script>

<template>
  <v-app>
    <v-app-bar app id="bar" class="top">
      <v-app-bar-title class="headline text-uppercase">
        <span class="font-weight-bold">Intuit</span>
        <span class="font-weight-light">Manager</span>
      </v-app-bar-title>

      <v-tabs v-model="index" class="nodrag">
        <v-spacer class="drag" />
        <v-tab v-for="tab in tabs" :key="tab.key">{{ tab.name }}</v-tab>
        <v-spacer class="drag" />
      </v-tabs>

      <v-btn @click="github" class="mr-2 nodrag">Github</v-btn>
      <v-btn @click="exitApp" color="blue-grey-darken-3" class="nodrag">Exit</v-btn>
    </v-app-bar>

    <v-window v-model="index" class="wrapper bottom" id="view">
      <!-- Home -->
      <v-window-item :value="0" class="wrapper">
        <div class="flex">
          <div class="main">
            <h1 class="display-2 font-weight-bold mb-3">Intuiter</h1>
            <svg @click="make" class="liquid-button" />
          </div>
        </div>
      </v-window-item>

      <!-- Option -->
      <v-window-item :value="1" class="wrapper">
        <div class="flex">
          <div class="main option-main">
            <v-switch label="Launch at startup" color="primary" />
            <v-switch label="Show in menu bar" color="primary" />
            <v-switch label="Enable notifications" color="primary" />
          </div>
        </div>
      </v-window-item>

      <!-- Shortcut -->
      <v-window-item :value="2" class="wrapper">
        <div class="flex">
          <div class="main shortcut-main">
            <v-table density="compact" class="shortcut-table">
              <thead>
                <tr>
                  <th>Shortcut</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <tr><td>Caps + H</td><td>Left Arrow</td></tr>
                <tr><td>Caps + J</td><td>Down Arrow</td></tr>
                <tr><td>Caps + K</td><td>Up Arrow</td></tr>
                <tr><td>Caps + L</td><td>Right Arrow</td></tr>
                <tr><td>Caps + U</td><td>Mouse Left</td></tr>
                <tr><td>Caps + I</td><td>Mouse Down</td></tr>
                <tr><td>Caps + O</td><td>Mouse Up</td></tr>
                <tr><td>Caps + P</td><td>Mouse Right</td></tr>
              </tbody>
            </v-table>
          </div>
        </div>
      </v-window-item>

      <!-- Extension -->
      <v-window-item :value="3" class="wrapper">
        <div class="flex">
          <div class="main ext-main">
            <v-list>
              <v-list-item title="Text Mode" subtitle="Caps + T to toggle" />
              <v-list-item title="Mouse Mode" subtitle="Caps + M to toggle" />
              <v-list-item title="Window Mode" subtitle="Caps + W to toggle" />
            </v-list>
          </div>
        </div>
      </v-window-item>

      <!-- Custom -->
      <v-window-item :value="4" class="wrapper">
        <div class="flex">
          <div class="main custom-main">
            <div v-for="(d, i) in digits" :key="d" class="mb-2">
              <v-text-field v-model="customPaths[i]" :label="`Cmd+${d}`" density="compact" variant="outlined" />
            </div>
            <v-btn color="primary">Save</v-btn>
          </div>
        </div>
      </v-window-item>

      <!-- Document -->
      <v-window-item :value="5" class="wrapper">
        <div class="flex docs-container">
          <iframe src="https://intuiter.vercel.app/en/usages/text.html" class="docs-iframe" />
        </div>
      </v-window-item>
    </v-window>

    <v-overlay :model-value="loading" class="loading-overlay">
      <v-progress-circular indeterminate size="64" />
    </v-overlay>
  </v-app>
</template>

<style>
::-webkit-scrollbar {
  display: none;
}

body {
  margin: 0 !important;
}

button {
  -webkit-app-region: no-drag;
}

.wrapper {
  height: 100%;
}

.flex {
  display: flex;
  height: 100%;
}

.top {
  flex: 1 0 auto;
}

.bottom {
  flex: 1 1 auto;
}

.drag {
  -webkit-app-region: drag;
}

.nodrag {
  -webkit-app-region: no-drag;
}

#view {
  background: #121314 !important;
}

#bar {
  -webkit-app-region: drag;
  border-radius: 10px;
  overflow: hidden;
}

.main {
  flex: 1 1 auto;
  margin-top: auto;
  margin-bottom: auto;
  text-align: center;
}

.liquid-button {
  width: 200px;
  height: 60px;
  cursor: pointer;
}

.docs-container {
  width: 100%;
  height: 100%;
}

.docs-iframe {
  width: 100%;
  height: 100%;
  border: none;
}

.loading-overlay {
  display: flex !important;
  align-items: center !important;
  justify-content: center !important;
}

.loading-overlay .v-overlay__content {
  position: static !important;
  display: flex !important;
  align-items: center !important;
  justify-content: center !important;
}

.custom-main {
  padding: 20px;
  max-width: 400px;
  margin: auto;
}

.option-main {
  padding: 20px;
  max-width: 300px;
}

.shortcut-main {
  padding: 20px;
  max-width: 400px;
}

.shortcut-table {
  background: transparent !important;
}

.ext-main {
  padding: 20px;
  max-width: 400px;
}
</style>

// src-react/App.tsx
import { useState, useEffect, useRef } from 'react'
import { invoke } from '@tauri-apps/api/core'
import { open } from '@tauri-apps/plugin-shell'
import { exit } from '@tauri-apps/plugin-process'
import DancingButton from 'dancing-button'

const tabs = ['Home', 'Option', 'Shortcut', 'Extension', 'Custom', 'Document']

export default function App() {
  const [activeTab, setActiveTab] = useState(0)
  const [loading, setLoading] = useState(false)
  const buttonRef = useRef<SVGSVGElement>(null)

  useEffect(() => {
    if (buttonRef.current) {
      new DancingButton(buttonRef.current)
    }
  }, [])

  async function handleStart() {
    setLoading(true)
    try {
      await invoke('spawn_input')
    } catch (e) {
      console.error(e)
    }
    setLoading(false)
  }

  async function handleGithub() {
    await open('https://github.com/seonglae/intuiter')
  }

  async function handleExit() {
    await exit(0)
  }

  return (
    <div className="h-full flex flex-col bg-background rounded-[30px] overflow-hidden">
      {/* Header */}
      <header className="flex items-center px-4 py-2 bg-zinc-900 rounded-t-[10px]" style={{ WebkitAppRegion: 'drag' } as React.CSSProperties}>
        <h1 className="text-lg uppercase tracking-wide mr-4">
          <span className="font-bold">Intuit</span>
          <span className="font-light">Manager</span>
        </h1>

        <nav className="flex-1 flex justify-center gap-1" style={{ WebkitAppRegion: 'no-drag' } as React.CSSProperties}>
          {tabs.map((tab, i) => (
            <button
              key={tab}
              onClick={() => setActiveTab(i)}
              className={`px-4 py-2 text-sm transition-colors ${
                activeTab === i
                  ? 'text-white border-b-2 border-white'
                  : 'text-zinc-400 hover:text-white'
              }`}
            >
              {tab}
            </button>
          ))}
        </nav>

        <div className="flex gap-2" style={{ WebkitAppRegion: 'no-drag' } as React.CSSProperties}>
          <button onClick={handleGithub} className="px-3 py-1 text-sm hover:text-zinc-300">
            Github
          </button>
          <button onClick={handleExit} className="px-3 py-1 text-sm hover:text-zinc-300">
            Exit
          </button>
        </div>
      </header>

      {/* Content */}
      <main className="flex-1 flex items-center justify-center">
        {activeTab === 0 && (
          <div className="text-center">
            <h1 className="text-4xl font-bold mb-6">Intuiter</h1>
            <svg ref={buttonRef} onClick={handleStart} className="w-[200px] h-[60px] cursor-pointer mx-auto" />
          </div>
        )}

        {activeTab === 1 && (
          <div className="text-center space-y-4">
            <label className="flex items-center justify-center gap-3">
              <input type="checkbox" className="w-4 h-4" />
              <span>Launch at startup</span>
            </label>
            <label className="flex items-center justify-center gap-3">
              <input type="checkbox" className="w-4 h-4" />
              <span>Show in menu bar</span>
            </label>
            <label className="flex items-center justify-center gap-3">
              <input type="checkbox" className="w-4 h-4" />
              <span>Enable notifications</span>
            </label>
          </div>
        )}

        {activeTab === 2 && (
          <div className="text-center">
            <table className="mx-auto text-left">
              <thead>
                <tr className="border-b border-zinc-700">
                  <th className="px-4 py-2">Shortcut</th>
                  <th className="px-4 py-2">Action</th>
                </tr>
              </thead>
              <tbody className="text-zinc-300">
                <tr><td className="px-4 py-1">Caps + H</td><td className="px-4 py-1">Left Arrow</td></tr>
                <tr><td className="px-4 py-1">Caps + J</td><td className="px-4 py-1">Down Arrow</td></tr>
                <tr><td className="px-4 py-1">Caps + K</td><td className="px-4 py-1">Up Arrow</td></tr>
                <tr><td className="px-4 py-1">Caps + L</td><td className="px-4 py-1">Right Arrow</td></tr>
                <tr><td className="px-4 py-1">Caps + U</td><td className="px-4 py-1">Mouse Left</td></tr>
                <tr><td className="px-4 py-1">Caps + I</td><td className="px-4 py-1">Mouse Down</td></tr>
                <tr><td className="px-4 py-1">Caps + O</td><td className="px-4 py-1">Mouse Up</td></tr>
                <tr><td className="px-4 py-1">Caps + P</td><td className="px-4 py-1">Mouse Right</td></tr>
              </tbody>
            </table>
          </div>
        )}

        {activeTab === 3 && (
          <div className="text-center space-y-2">
            <div className="p-3 bg-zinc-800 rounded">
              <div className="font-medium">Text Mode</div>
              <div className="text-sm text-zinc-400">Caps + T to toggle</div>
            </div>
            <div className="p-3 bg-zinc-800 rounded">
              <div className="font-medium">Mouse Mode</div>
              <div className="text-sm text-zinc-400">Caps + M to toggle</div>
            </div>
            <div className="p-3 bg-zinc-800 rounded">
              <div className="font-medium">Window Mode</div>
              <div className="text-sm text-zinc-400">Caps + W to toggle</div>
            </div>
          </div>
        )}

        {activeTab === 4 && (
          <div className="text-center space-y-3 w-80">
            {['1','2','3','4','5','6','7','8','9','0'].map((d, i) => (
              <div key={d} className="flex items-center gap-2">
                <label className="w-16 text-right text-zinc-400">Cmd+{d}</label>
                <input type="text" className="flex-1 px-3 py-1 bg-zinc-800 border border-zinc-700 rounded text-sm" />
              </div>
            ))}
            <button className="mt-4 px-6 py-2 bg-blue-600 hover:bg-blue-500 rounded">Save</button>
          </div>
        )}

        {activeTab === 5 && (
          <iframe
            src="https://intuiter.vercel.app/en/usages/text.html"
            className="w-full h-full border-none"
          />
        )}
      </main>

      {/* Loading overlay */}
      {loading && (
        <div className="absolute inset-0 flex items-center justify-center bg-black/50">
          <div className="w-12 h-12 border-4 border-white border-t-transparent rounded-full animate-spin" />
        </div>
      )}
    </div>
  )
}
